[server]
data-path = "Data/raft-kvs"
log-path = "Logs/raft-kvs"
log-level = "info"

[cluster]
[[cluster.nodes]]
node-id=1
host="localhost"
http-port=6479
heartbeat-port=6480
replicate-port=6481

[[cluster.nodes]]
node-id=2
host="localhost"
http-port=6579
heartbeat-port=6580
replicate-port=6581

[[cluster.nodes]]
node-id=3
host="localhost"
http-port=6679
heartbeat-port=6680
replicate-port=6681

# [[cluster.nodes]]
# node-id=4
# host="n4"
# http-port=9991
# heartbeat-port=9992
# replicate-port=9993

# [[cluster.nodes]]
# node-id=5
# host="n5"
# http-port=9991
# heartbeat-port=9992
# replicate-port=9993
